name: Build

on:
  push:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-16.04, ubuntu-22.04 ]
        php: [ 5.6, 8.1 ]
        exclude:
          - os: ubuntu-16.04
            php: 8.1
          - os: ubuntu-22.04
            php: 5.6

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, openssl, pdo, pdo_mysql, mailparse, iconv, gd, zlib, curl, xml, simplexml, dom, calendar, gettext, zip, tidy, intl

      - uses: actions/checkout@v3
        with:
          path: main

      - name: Build Swig v4
        if: matrix.php == '8.1'
        run: |
          git clone https://github.com/swig/swig.git
          cd swig
          mkdir Build
          cd Build
          cmake ..
          make
          sudo make install

      - name: Build Swig v2
        if: matrix.php == '5.6'
        run: |
          wget https://github.com/swig/swig/archive/refs/tags/v2.0.12.tar.gz
          tar xzvf v2.0.12.tar.gz
          sudo apt-get install automake build-essential libtool libpcre3-dev libpcre3 bison flex
          ./autogen.sh
          ./configure
          make
          sudo make install
          swig -version

      - name: Clone PDFTron
        run: |
          mkdir wrappers_build # Make a directory to build the wrappers in.
          cd wrappers_build # Move to that directory.
          git clone https://github.com/PDFTron/PDFNetWrappers # Git the code.

      - name: Run build
        run: python3 build.py --custom_swig=/usr/local/bin/swig
