name: Build

on:
  push:
    branches:
      - 'ubuntu-*'

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-22.04 ]
        php: [ 5.6, 8.1 ]
        exclude:
          - os: ubuntu-18.04
            php: 8.1
          - os: ubuntu-22.04
            php: 5.6

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, openssl, pdo, pdo_mysql, mailparse, iconv, gd, zlib, curl, xml, simplexml, dom, calendar, gettext, zip, tidy, intl

      - uses: actions/checkout@v3
        with:
          path: main

      - name: Build Swig v4
        if: matrix.php == '8.1'
        run: |
          git clone https://github.com/swig/swig.git
          cd swig
          mkdir Build
          cd Build
          cmake ..
          make
          sudo make install
          swig -version
          /usr/local/bin/swig -version

      - name: Build Swig v2
        if: matrix.php == '5.6'
        run: |
          sudo apt-get install automake build-essential libtool libpcre3-dev libpcre3 bison flex
          mkdir swig
          wget -q https://github.com/swig/swig/archive/refs/tags/v2.0.12.tar.gz
          tar xzf v2.0.12.tar.gz
          cd swig-2.0.12
          ./autogen.sh
          ./configure
          make
          sudo make install
          swig -version
          /usr/local/bin/swig -version

      - name: Clone PDFTron
        run: |
          mkdir wrappers_build # Make a directory to build the wrappers in.
          cd wrappers_build # Move to that directory.
          git clone https://github.com/PDFTron/PDFNetWrappers # Git the code.

      - name: CMake
        run: |
          rsync -avhW main/build.py wrappers_build/PDFNetWrappers/build.py
          cd wrappers_build/PDFNetWrappers/ 
          python3 build.py --custom_swig=/usr/local/bin/swig --wrapper=PDFNetPHP

      - name: Make
        run: |
          cd wrappers_build/PDFNetWrappers/build/
          make

      - name: Commit SO file
        run: |
          mkdir -p main/${{ matrix.os }}/${{ matrix.php }}
          cp wrappers_build/PDFNetWrappers/build/lib/PDFNetPHP.so main/${{ matrix.os }}/${{ matrix.php }}/
          
          cd main/
          
          git checkout -b ${{ matrix.os }}-${{ matrix.php }}
          
          git add .

          git config --local user.email "gha@uniques.ca"
          git config --local user.name "GitHub Actions"

          git diff-index --quiet HEAD || (git commit -a -m "Automatic commit for the build wrapper for ${{ matrix.os }}/${{ matrix.php }}: #${GITHUB_SHA}" && git push)

      - if: always()
        run: cat wrappers_build/PDFNetWrappers/build/CMakeFiles/CMakeOutput.log

      - name: See compiled stuff
        if: always()
        run: |
          ls -al wrappers_build/PDFNetWrappers/build/
          ls -al wrappers_build/PDFNetWrappers/build/PDFNetPHP/
          
